
SCRIPTS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))

TB=simple_dpi_tb


include $(ROOTDIR)/common/common_sim.mk

# SIM_DATAFILES += $(call get_plusarg,SW_IMAGE,$(PLUSARGS))
# UVM_TESTNAME := $(call get_plusarg,UVM_TESTNAME,$(PLUSARGS))

